version: '3.8'
services:

  scrapy:
    image: klauswarzecha/scrapy:2.7.1
    build: ./scrapy
    container_name: scrapy
    hostname: scrapy
    environment: 
      - TZ=Europe/Berlin
    ports:
      - mode: host
        protocol: tcp
        published: 6800
        target: 6800 
    networks:
      - crawling
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.11.3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
    env_file: 
      - ./env/rabbbitmq.env
    networks:
      - crawling
    volumes: 
      - type: volume
        source: rabbitmqdata
        target: /var/lib/rabbitmq/data

  medusa:
    image: datawookie/medusa-proxy:latest
    container_name: medusa
    hostname: medusa
    networks:
      - crawling
    environment:
      - HEADS=4
      - TORS=3
    ports:
      - 1080:1080
	    - 2090:2090
      - 8800:8800
      - 8888:8888
      - 8889:8889
      - 8890:8890
      - 8891:8891


networks:
  crawling:

volumes:
  rabbitmqdata:
    